export const GOODS = [
  { id: 'rum',     name: 'Rum',      basePrice: 20,  weight: 1 },
  { id: 'spices',  name: 'Gewürze',   basePrice: 50,  weight: 1 },
  { id: 'wood',    name: 'Holz',     basePrice: 15,  weight: 1 },
  { id: 'iron',    name: 'Eisen',     basePrice: 35,  weight: 1 },
  { id: 'cloth',   name: 'Stoffe',    basePrice: 25,  weight: 1 },
  { id: 'tobacco', name: 'Tabak',  basePrice: 30,  weight: 1 },
];

// multiplier tables: buy = base * buyMul, sell = base * sellMul
export const PORTS = [
  {
    id: 'port_haven',
    name: 'Port Haven',
    x: 320,
    y: 280,
    desc: 'Ein belebter Handelsknotenpunkt, bekannt für seine feinen Rum-Brennereien.',
    prices: {
      rum:     { buy: 0.7, sell: 0.6 },
      spices:  { buy: 1.4, sell: 1.2 },
      wood:    { buy: 1.1, sell: 0.9 },
      iron:    { buy: 1.8, sell: 1.5 },
      cloth:   { buy: 1.2, sell: 1.0 },
      tobacco: { buy: 1.3, sell: 1.1 },
    },
  },
  {
    id: 'redreef',
    name: 'Redreef',
    x: 680,
    y: 180,
    desc: 'Ein Holzhafen, umgeben von alten roten Riffen.',
    prices: {
      rum:     { buy: 1.3, sell: 1.1 },
      spices:  { buy: 1.5, sell: 1.2 },
      wood:    { buy: 0.6, sell: 0.5 },
      iron:    { buy: 1.2, sell: 1.0 },
      cloth:   { buy: 1.8, sell: 1.5 },
      tobacco: { buy: 1.2, sell: 1.0 },
    },
  },
  {
    id: 'san_cordoba',
    name: 'San Cordoba',
    x: 520,
    y: 480,
    desc: 'Eine reiche Kolonialstadt, berühmt für ihre feinen Stoffe.',
    prices: {
      rum:     { buy: 1.2, sell: 1.0 },
      spices:  { buy: 1.3, sell: 1.1 },
      wood:    { buy: 1.9, sell: 1.6 },
      iron:    { buy: 1.3, sell: 1.1 },
      cloth:   { buy: 0.7, sell: 0.6 },
      tobacco: { buy: 1.4, sell: 1.2 },
    },
  },
  {
    id: 'blackwater_cay',
    name: 'Blackwater Cay',
    x: 860,
    y: 420,
    desc: 'Ein Schmugglernest, in dem der Tabak in Strömen fließt.',
    prices: {
      rum:     { buy: 1.1, sell: 0.9 },
      spices:  { buy: 1.9, sell: 1.6 },
      wood:    { buy: 1.2, sell: 1.0 },
      iron:    { buy: 1.4, sell: 1.2 },
      cloth:   { buy: 1.3, sell: 1.1 },
      tobacco: { buy: 0.65, sell: 0.55 },
    },
  },
  {
    id: 'kingsport',
    name: 'Kingsport',
    x: 180,
    y: 520,
    desc: 'Eine Marinestützpunkt mit einer blühenden Eisengießerei.',
    prices: {
      rum:     { buy: 1.8, sell: 1.5 },
      spices:  { buy: 1.2, sell: 1.0 },
      wood:    { buy: 1.3, sell: 1.1 },
      iron:    { buy: 0.65, sell: 0.55 },
      cloth:   { buy: 1.1, sell: 0.9 },
      tobacco: { buy: 1.2, sell: 1.0 },
    },
  },
  {
    id: 'isla_verde',
    name: 'Isla Verde',
    x: 720,
    y: 600,
    desc: 'Eine tropische Insel, die vor exotischen Gewürzen überquillt.',
    prices: {
      rum:     { buy: 1.4, sell: 1.2 },
      spices:  { buy: 0.6, sell: 0.5 },
      wood:    { buy: 1.1, sell: 0.9 },
      iron:    { buy: 1.5, sell: 1.3 },
      cloth:   { buy: 1.2, sell: 1.0 },
      tobacco: { buy: 1.9, sell: 1.6 },
    },
  },
];

export const UPGRADES = [
  {
    id: 'hull',
    name: 'Rumpfverstärkung',
    desc: 'Erhöht den maximalen Rumpf und repariert etwas Schaden.',
    maxLevel: 4,
    effect: (lvl) => ({ maxHull: 20 * lvl, hullRepair: 10 * lvl }),
    price: (lvl) => 200 + lvl * 300,
  },
  {
    id: 'cannons',
    name: 'Schwere Kanonen',
    desc: 'Mehr Feuerkraft im Kampf.',
    maxLevel: 4,
    effect: (lvl) => ({ cannons: lvl * 2 }),
    price: (lvl) => 250 + lvl * 350,
  },
  {
    id: 'sails',
    name: 'Schnelle Segel',
    desc: 'Erhöht die Geschwindigkeit und Fluchtchance.',
    maxLevel: 4,
    effect: (lvl) => ({ speed: lvl * 30 }),
    price: (lvl) => 200 + lvl * 250,
  },
  {
    id: 'cargo',
    name: 'Erweiterter Frachtraum',
    desc: 'Erhöht die Frachtkapazität.',
    maxLevel: 4,
    effect: (lvl) => ({ cargoCapacity: lvl * 10 }),
    price: (lvl) => 180 + lvl * 200,
  },
];

export const RUMORS = [
  'Rum ist in Port Haven oft billig.',
  'Eisen erzielt in Kingsport gute Preise... warte, nein — Port Haven zahlt am besten dafür!',
  'Gewürze von Isla Verde verkaufen sich gut in Blackwater Cay.',
  'Die Route vorbei an Blackwater Cay zieht Piraten an.',
  'In San Cordoba gewebte Stoffe sind in Redreef hochgeschätzt.',
  'Aus Blackwater Cay geschmuggelter Tabak wird in Isla Verde für ein Vermögen verkauft.',
  'Holz aus Redreef ist in San Cordoba Mangelware.',
  'Die Marine patrouilliert in den Gewässern nahe Kingsport.',
  'Ein Händler mit wertvollen Gewürzen wurde nahe Isla Verde gesichtet.',
  'Nördlich von Redreef brauen sich häufig Stürme zusammen.',
];

export const INITIAL_PLAYER = {
  name: 'Seefalke',
  gold: 500,
  hull: 100,
  maxHull: 100,
  cannons: 2,
  speed: 100,
  cargoCapacity: 20,
  cargo: {},
  crew: 8,
  maxCrew: 12,
  morale: 70,
  reputation: 0,
  x: 320,
  y: 280,
  day: 1,
  enemiesDefeated: 0,
  upgradeLevel: { hull: 0, cannons: 0, sails: 0, cargo: 0 },
};
