export const GOODS = [
  { id: 'rum',     name: 'Rum',      basePrice: 20,  weight: 1 },
  { id: 'spices',  name: 'Spices',   basePrice: 50,  weight: 1 },
  { id: 'wood',    name: 'Wood',     basePrice: 15,  weight: 1 },
  { id: 'iron',    name: 'Iron',     basePrice: 35,  weight: 1 },
  { id: 'cloth',   name: 'Cloth',    basePrice: 25,  weight: 1 },
  { id: 'tobacco', name: 'Tobacco',  basePrice: 30,  weight: 1 },
];

// multiplier tables: buy = base * buyMul, sell = base * sellMul
export const PORTS = [
  {
    id: 'port_haven',
    name: 'Port Haven',
    x: 320,
    y: 280,
    desc: 'A busy trading hub known for its fine rum distilleries.',
    prices: {
      rum:     { buy: 0.7, sell: 0.6 },
      spices:  { buy: 1.4, sell: 1.2 },
      wood:    { buy: 1.1, sell: 0.9 },
      iron:    { buy: 1.8, sell: 1.5 },
      cloth:   { buy: 1.2, sell: 1.0 },
      tobacco: { buy: 1.3, sell: 1.1 },
    },
  },
  {
    id: 'redreef',
    name: 'Redreef',
    x: 680,
    y: 180,
    desc: 'A timber port surrounded by ancient red reefs.',
    prices: {
      rum:     { buy: 1.3, sell: 1.1 },
      spices:  { buy: 1.5, sell: 1.2 },
      wood:    { buy: 0.6, sell: 0.5 },
      iron:    { buy: 1.2, sell: 1.0 },
      cloth:   { buy: 1.8, sell: 1.5 },
      tobacco: { buy: 1.2, sell: 1.0 },
    },
  },
  {
    id: 'san_cordoba',
    name: 'San Cordoba',
    x: 520,
    y: 480,
    desc: 'A wealthy colonial port famed for its fine cloth.',
    prices: {
      rum:     { buy: 1.2, sell: 1.0 },
      spices:  { buy: 1.3, sell: 1.1 },
      wood:    { buy: 1.9, sell: 1.6 },
      iron:    { buy: 1.3, sell: 1.1 },
      cloth:   { buy: 0.7, sell: 0.6 },
      tobacco: { buy: 1.4, sell: 1.2 },
    },
  },
  {
    id: 'blackwater_cay',
    name: 'Blackwater Cay',
    x: 860,
    y: 420,
    desc: 'A smuggler\'s den where tobacco flows freely.',
    prices: {
      rum:     { buy: 1.1, sell: 0.9 },
      spices:  { buy: 1.9, sell: 1.6 },
      wood:    { buy: 1.2, sell: 1.0 },
      iron:    { buy: 1.4, sell: 1.2 },
      cloth:   { buy: 1.3, sell: 1.1 },
      tobacco: { buy: 0.65, sell: 0.55 },
    },
  },
  {
    id: 'kingsport',
    name: 'Kingsport',
    x: 180,
    y: 520,
    desc: 'A naval stronghold with a thriving iron foundry.',
    prices: {
      rum:     { buy: 1.8, sell: 1.5 },
      spices:  { buy: 1.2, sell: 1.0 },
      wood:    { buy: 1.3, sell: 1.1 },
      iron:    { buy: 0.65, sell: 0.55 },
      cloth:   { buy: 1.1, sell: 0.9 },
      tobacco: { buy: 1.2, sell: 1.0 },
    },
  },
  {
    id: 'isla_verde',
    name: 'Isla Verde',
    x: 720,
    y: 600,
    desc: 'A tropical island overflowing with exotic spices.',
    prices: {
      rum:     { buy: 1.4, sell: 1.2 },
      spices:  { buy: 0.6, sell: 0.5 },
      wood:    { buy: 1.1, sell: 0.9 },
      iron:    { buy: 1.5, sell: 1.3 },
      cloth:   { buy: 1.2, sell: 1.0 },
      tobacco: { buy: 1.9, sell: 1.6 },
    },
  },
];

export const UPGRADES = [
  {
    id: 'hull',
    name: 'Hull Reinforcement',
    desc: 'Increases max hull and repairs some damage.',
    maxLevel: 4,
    effect: (lvl) => ({ maxHull: 20 * lvl, hullRepair: 10 * lvl }),
    price: (lvl) => 200 + lvl * 300,
  },
  {
    id: 'cannons',
    name: 'Heavy Cannons',
    desc: 'More firepower in battle.',
    maxLevel: 4,
    effect: (lvl) => ({ cannons: lvl * 2 }),
    price: (lvl) => 250 + lvl * 350,
  },
  {
    id: 'sails',
    name: 'Swift Sails',
    desc: 'Increases speed and escape chance.',
    maxLevel: 4,
    effect: (lvl) => ({ speed: lvl * 30 }),
    price: (lvl) => 200 + lvl * 250,
  },
  {
    id: 'cargo',
    name: 'Expanded Hold',
    desc: 'Increases cargo capacity.',
    maxLevel: 4,
    effect: (lvl) => ({ cargoCapacity: lvl * 10 }),
    price: (lvl) => 180 + lvl * 200,
  },
];

export const RUMORS = [
  'Rum is often cheap in Port Haven.',
  'Iron fetches good prices in Kingsport... wait, no — Port Haven pays top coin for it!',
  'Spices from Isla Verde sell well in Blackwater Cay.',
  'The route past Blackwater Cay attracts pirates.',
  'Cloth woven in San Cordoba is prized in Redreef.',
  'Tobacco smuggled from Blackwater Cay sells for a fortune in Isla Verde.',
  'Wood from Redreef is scarce in San Cordoba.',
  'Marines patrol the waters near Kingsport.',
  'A merchant was spotted near Isla Verde carrying valuable spices.',
  'Storms brew frequently north of Redreef.',
];

export const INITIAL_PLAYER = {
  name: 'Sea Hawk',
  gold: 500,
  hull: 100,
  maxHull: 100,
  cannons: 2,
  speed: 100,
  cargoCapacity: 20,
  cargo: {},
  crew: 8,
  maxCrew: 12,
  morale: 70,
  reputation: 0,
  x: 320,
  y: 280,
  day: 1,
  enemiesDefeated: 0,
  upgradeLevel: { hull: 0, cannons: 0, sails: 0, cargo: 0 },
};
